### ISSUE TITLE
Turn the button into an styled component

### ISSUE THREAD

**Issue by mohammadrajabraza** [mohammadrajabraza/styled-button#3]
# Expected Behavior
Style the button using [styled-component](https://styled-components.com/).

## Requirements

- [ ] Button should be styled using styled-component
- [ ] These styles should be applied initially
- `height : 36px`, should be set using `padding` (i.e. `padding-top `, `padding-bottom`) : `6px`
-  `horiontal-padding` (i.e. `padding-left`, `padding-right`) : `12px` 
- `width` : should be auto
- `background-color : #01579b`
- `color : #fff`
- `font-size : 16px`
- `line-height : 24px`
- `border-radius : 5px`
- `border : 1px solid #01579b`

**Comment by sunidhisachan** [comment]
Hey @mohammadrajabraza I can try this. Please assign this to me.

**Comment by mohammadrajabraza** [comment]
Welcome @sunidhisachan  ! Looking forward to receiving your PR soon.

**Comment by mohammadrajabraza** [comment]
@sunidhisachan what's the update on PR?
