### ISSUE TITLE
Hover state for the button

### ISSUE THREAD

**Issue by mohammadrajabraza** [mohammadrajabraza/styled-button#4]
# Expected Behavior
Add a hover state style for the button

## Requirements

- [ ] These style(s) should be applied for hover state
- `background-color : #0d47a1`
- `border-color : #0d47a1`

**Comment by sunidhisachan** [comment]
hey @mohammadrajabraza I can try this.

**Comment by mohammadrajabraza** [comment]
Please complete the first one first, so we can start working on this.

**Comment by stack-queue-coder** [comment]
Kindly let me contribute to this issue
