### ISSUE TITLE
Remove irrelevant links and instructions from the CONTRIBUTING.md

### ISSUE THREAD

**Issue by mohammadrajabraza** [mohammadrajabraza/styled-button#8]
# Expected Behavior
`CONTRIBUTING.md` should only contain relevant content 

## Requirements

- [ ] Replace the new issue link from another repository to this repository
- [ ] Remove the 3rd instruction from the Guidelines' section **Issues and Pull Requests**

**Comment by abritpal** [comment]
can I take up this issue

**Comment by mohammadrajabraza** [comment]
Sorry @abritpal . PR already submitted for this Issue.

**Comment by abritpal** [comment]
ok cool, can you assign me this one ->  https://github.com/mohammadrajabraza/styled-button/issues/7
